services:
    nginx:
        container_name: nginx
        hostname: nginx
        image: nginx:latest
        ports:
            - 8449:80
        restart: always
        tty: true
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/keys:/etc/nginx/keys
            - ./nginx/statics:/etc/nginx/static/statics
    pocketbasec:
        build: ./pocketbase_custom
        container_name: template_pocketbasec
        hostname: pocketbasec
        restart: always
        tty: true
        volumes:
            - ./pocketbase_custom/src:/root/pocketbase
            - ./pocketbase_custom/pbdata:/pocketbase/pb_data
    redis:
        hostname: redis
        image: redis:latest
        restart: always
        volumes:
            - ./databases/MainRedis:/data
