services:  
    template_nginx:
        restart: always
        image: nginx:latest
        container_name: template_nginx
        ports:
            - "8449:80"
        volumes:
            # NGINXのコンフィグファイルをホストOSから、ゲストOSに連結する
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/keys:/etc/nginx/keys
            - ./nginx/statics:/etc/nginx/static/statics
        tty: true
        hostname: nginx

    redis:
        image: "redis:latest"
        volumes:
            - "./databases/MainRedis:/data"
        restart: always
        hostname: redis

    pocketbasec:
        container_name: template_pocketbasec
        build: ./pocketbase_custom
        volumes:
            - ./pocketbase_custom/src:/root/pocketbase
            - ./pocketbase_custom/pbdata:/pocketbase/pb_data
        tty: true
        restart: always
        hostname: pocketbasec
    